### ISSUE TITLE
Dear Roca

### ISSUE THREAD

**Issue by aurora5161** [jugg1es/Bedbot#1]
Thank you for your project, When I run the code on my computer (system is ubuntu), I get some mistakes below, could you do me a favor? Thank you very much

Adafruit OLED libraries not found
has IO libraries (screen manager): False
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/home/luop/Downloads/Bedbot/Modules/Widgets/AlarmWidget.py", line 136, in initializeAlarmPresets
    parent.alarmSettings = parent.configManager.loadSettings()
  File "/home/luop/Downloads/Bedbot/Modules/Objects/alarmConfig.py", line 44, in loadSettings
    self.config.set(section, "status", str(AlarmState.OFF.value))
AttributeError: 'int' object has no attribute 'value'

**Comment by jugg1es** [comment]
It looks like AlarmState.py isn't being imported correctly.  alarmConfig.py imports alarmSetting.py, which should import AlarmState.py.  You could try adding the import to alarmConfig.py.  Try adding

```
from Modules.Objects.AlarmState import * 
```

to alarmConfig.py.

**Comment by jugg1es** [comment]
Actually I just remembered why this error appears.  It has to do the enum library you're using and the version of Python you're using.  This was built using python 2.7 and the enum library from python 3 doesn't work right (if I remember correctly).

**Comment by aurora5161** [comment]
Thank you very much ,Dear Roca! These days I was busy with my study, I'm sorry to reply to you today!
